### ISSUE TITLE
Color phylogenetic tree branches according to species name

### ISSUE THREAD

**Issue by WenChangYu** [jokergoo/spiralize#41]
I am using spiralize package to visualize phylogenetic tree. 
By reading the manual, I found the color_branches( ) function can color branches according to h or k parameters.

 Here I want to know is there any function can color branches according to species name, which I think is very important information in phylogenetic analyses.

Thanks in advance.

**Comment by jokergoo** [comment]
> Here I want to know is there any function can color branches according to species name, which I think is very important information in phylogenetic analyses.

I think it is mainly a thing of how you group the leaves of the dendrogram. It should be not difficult to be done with **dendextend** package. See the section "Adjusting branches based on labels" on https://cran.r-project.org/web/packages/dendextend/vignettes/dendextend.html. Then the "rendered" `dend` object can be used in `spiral_dendrogram()`.
